// Sources reviewed for the project's original four research families.
// A reference supports its stated finding, not every recipe shown beside it.
export const RESEARCH_REVIEW_DATE = "2026-09-05";

export const EVIDENCE_SOURCES = [
  {
    id: "who2023",
    label: "WHO 2023: complementary feeding guideline",
    url: "https://www.ncbi.nlm.nih.gov/books/NBK596423/",
    family: "WHO 2023",
    type: "Guideline",
    ageRange: "6–23 months, including specific 12–23-month recommendations",
    finding: "Daily meat, fish or eggs and daily fruit and vegetables; frequent pulses, nuts and seeds. Avoid a starch-dominated diet and support responsive feeding.",
    limitations: "Population guidance, generally low-certainty evidence. Does not prescribe this menu, meat at every meal, a vegetable-to-fruit ratio or individual food quantities.",
    provenance: "Identifiable original source family; current guideline checked in the age-specific review.",
  },
  {
    id: "whoResponsive",
    label: "WHO evidence review: responsive feeding (IECS, 2021)",
    url: "https://cdn.who.int/media/docs/default-source/nutrition-and-food-safety/complementary-feeding/cf-guidelines/systematic-review-responsive-feeding.pdf?sfvrsn=2a46329d_3",
    family: "WHO 2023",
    type: "Commissioned systematic review",
    ageRange: "Children under 2; selected outcomes at 20–23 months",
    finding: "Reviewed 26 randomised trials. Interventions included hunger/fullness cues, avoiding pressure and encouraging self-feeding; some improved observed feeding behaviours.",
    limitations: "Interventions and effects varied. Does not validate fixed portions, diagnose appetite or guarantee adequate intake.",
    provenance: "Further primary evidence commissioned for the original WHO guideline family.",
  },
  {
    id: "whoMilk",
    label: "WHO evidence review: milks at 12–23 months",
    url: "https://cdn.who.int/media/docs/default-source/nutrition-and-food-safety/complementary-feeding/cf-guidelines/systematic-review-milks-12-23-months.pdf?sfvrsn=f968c9f2_3",
    family: "WHO 2023",
    type: "Commissioned systematic review",
    ageRange: "12–23 months; mainly apparently healthy children",
    finding: "Informs the conditional WHO milk recommendation. Evidence comparing animal and plant milks was very limited.",
    limitations: "The plant-versus-animal comparison included one 21-participant blood-lipid trial. It does not establish a nutritionally adequate milk replacement or a cow’s-milk-allergy treatment plan.",
    provenance: "Further evidence commissioned for the original WHO guideline family.",
  },
  {
    id: "leap",
    label: "LEAP: peanut consumption regimen (2015)",
    url: "https://www.leapstudy.co.uk/leap-0.html",
    family: "LEAP",
    type: "Randomised trial and trial-team protocol summary",
    ageRange: "Enrolled at 4 to under 11 months; consumption continued to age 5",
    finding: "In 640 high-risk infants, early consumption reduced peanut allergy at age 5. The regimen was 6 g of peanut protein per week across at least three meals.",
    limitations: "Peanut-protein grams are not peanut-butter grams. Not a minimum-dose trial, a first-introduction trial at 12–23 months or treatment of existing allergy; baseline screening/challenges were used.",
    provenance: "Identifiable original source family; toddler relevance is maintenance after infant introduction.",
  },
  {
    id: "leapOn",
    label: "LEAP-On: avoidance after early consumption (2016)",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12333932/",
    family: "LEAP",
    type: "Randomised-trial follow-up",
    ageRange: "Ages 5–6, after consumption from infancy to age 5",
    finding: "After a year of avoidance, allergy remained lower in the original consumption group: 4.8% versus 18.6%.",
    limitations: "The minimum prior duration for stable tolerance was unknown. No toddler stopping, missed-week or catch-up rule follows from this study.",
    provenance: "Follow-up within the original LEAP source family; not an independent replication.",
  },
  {
    id: "leapTrio",
    label: "LEAP-Trio: follow-up to adolescence (2024)",
    url: "https://pubmed.ncbi.nlm.nih.gov/38804779/",
    family: "LEAP",
    type: "Long-term trial-cohort follow-up",
    ageRange: "Age-12 assessment after infant intervention",
    finding: "Peanut allergy was 4.4% in former consumers versus 15.4% in former avoiders.",
    limitations: "Outcomes were available for 497 of 640 original participants; later intake was family-selected. Does not establish a toddler restart schedule.",
    provenance: "Further follow-up within the original LEAP source family.",
  },
  {
    id: "leapSpecificity",
    label: "LEAP: allergen specificity analysis (2018)",
    url: "https://kclpure.kcl.ac.uk/portal/en/publications/allergen-specificity-of-early-peanut-consumption-and-effect-on-de/",
    family: "LEAP",
    type: "Trial-cohort analysis",
    ageRange: "Infant-start LEAP cohort followed through childhood",
    finding: "The preventive effect was peanut-specific; peanut consumption did not prevent other allergic disease or accelerate egg-allergy resolution.",
    limitations: "Does not establish egg, sesame, fish, milk or tree-nut exposure quotas.",
    provenance: "Further analysis within the original LEAP source family.",
  },
  {
    id: "blissProtocol",
    label: "NZ BLISS: feeding intervention protocol (Daniels, 2015)",
    url: "https://link.springer.com/article/10.1186/s12887-015-0491-8",
    family: "NZ BLISS",
    type: "Randomised-trial protocol",
    ageRange: "Supported feeding from around 6 months; follow-up to 24 months",
    finding: "Meals included iron-rich food, energy-rich food and easy-to-eat fruit or vegetables, alongside responsive self-feeding and preparation teaching.",
    limitations: "A supported intervention begun in infancy. The app’s recipes, portions and toddler texture adaptations are not a published BLISS menu or a nutritional assessment.",
    provenance: "Identifiable original source family; protocol separated from outcome findings.",
  },
  {
    id: "blissIron",
    label: "NZ BLISS: iron intake and status (Daniels, 2018)",
    url: "https://bmjopen.bmj.com/content/8/6/e019036",
    family: "NZ BLISS",
    type: "Randomised-trial outcome analysis",
    ageRange: "Iron intake at 7/12 months; blood measures at 12 months",
    finding: "No significant between-group differences in iron intake or status; 83% in each group were iron sufficient.",
    limitations: "Blood samples from 119 children, fewer than planned. Deficiency occurred in both groups; neither BLISS nor a meal checkbox guarantees iron adequacy.",
    provenance: "Outcome paper from the original BLISS trial family; not an independent replication.",
  },
  {
    id: "blissGrowth",
    label: "NZ BLISS: growth and overweight (Taylor, 2017)",
    url: "https://pubmed.ncbi.nlm.nih.gov/28692728/",
    family: "NZ BLISS",
    type: "Randomised-trial outcome analysis",
    ageRange: "Outcomes at 12 and 24 months",
    finding: "No significant differences in BMI z-score or energy intake. Parents reported less fussiness and more enjoyment at 12 months.",
    limitations: "166 participants available at 24 months. Did not demonstrate obesity prevention, superior growth or better energy self-regulation.",
    provenance: "Outcome paper from the same BLISS trial.",
  },
  {
    id: "blissChoking",
    label: "NZ BLISS: choking outcomes (Fangupo, 2016)",
    url: "https://pubmed.ncbi.nlm.nih.gov/27647715/",
    family: "NZ BLISS",
    type: "Randomised-trial outcome analysis",
    ageRange: "Parent-reported observations through 12 months",
    finding: "No significant group difference in reported choking was detected with the supported BLISS intervention.",
    limitations: "Choking still occurred. Does not establish zero risk, a toddler choking rate or the safety of every self-feeding approach.",
    provenance: "Outcome paper from the same BLISS trial.",
  },
  {
    id: "blissDiet",
    label: "NZ BLISS: food and nutrient intake (Erickson, 2018)",
    url: "https://www.mdpi.com/2072-6643/10/6/740",
    family: "NZ BLISS",
    type: "Randomised-trial dietary analysis",
    ageRange: "Diet assessed through 24 months",
    finding: "Nutrient intakes were broadly similar at 24 months; high sodium and added-sugar intake remained common.",
    limitations: "Family meals did not automatically produce an ideal diet. A food or recipe name cannot establish nutrient adequacy.",
    provenance: "Outcome paper from the same BLISS trial.",
  },
  {
    id: "blissVariety",
    label: "NZ BLISS: food variety and preferences (Morison, 2018)",
    url: "https://pubmed.ncbi.nlm.nih.gov/30111722/",
    family: "NZ BLISS",
    type: "Randomised-trial dietary analysis",
    ageRange: "Outcomes through 24 months",
    finding: "At 24 months, BLISS children ate about two more distinct fruit/vegetable foods across three recording days.",
    limitations: "Substantial loss of dietary records; does not establish lifelong preferences or developmental benefit.",
    provenance: "Outcome paper from the same BLISS trial.",
  },
  {
    id: "nordic2023",
    label: "Nordic Nutrition Recommendations 2023: 12–23 months",
    url: "https://pub.norden.org/nord2023-003/recommendations.html",
    family: "Scandinavian / Nordic",
    type: "Nutrition recommendations",
    ageRange: "Specific 12–23-month ranges",
    finding: "Of total dietary energy: protein 10–15%, fat 30–40%, carbohydrate 45–60%. Fat quality matters; saturated-fat guidance applies from 12 months.",
    limitations: "Whole-diet planning ranges including milk feeds, not per-meal quotas or a recommendation for unrestricted fat.",
    provenance: "Newly identified within the permitted Nordic family; not confirmed as an originally selected document.",
  },
  {
    id: "nordicIntakes",
    label: "NNR2023 Appendix 6: single-year 1 y reference intakes",
    url: "https://pub.norden.org/nord2023-003/appendix.html",
    family: "Scandinavian / Nordic",
    type: "Nutrient reference values",
    ageRange: "Single-year 1 y row (12–23 months)",
    finding: "Recommended usual total intake: iron 7 mg/day, vitamin D 10 micrograms/day, calcium 400 mg/day and zinc 4.0 mg/day.",
    limitations: "Not supplement prescriptions or a diagnosis from a day’s log. The broader 1–3-year row has different calcium and zinc values.",
    provenance: "Newly identified within the permitted Nordic family; age-specific row checked separately.",
  },
  {
    id: "otis",
    label: "Swedish OTIS: Nordic complementary diet (Johansson, 2023)",
    url: "https://www.repository.cam.ac.uk/items/13465d77-143f-491a-8863-ebeda9d24206",
    family: "Scandinavian / Nordic",
    type: "Randomised trial",
    ageRange: "Infant-start intervention; outcomes at 12 and 18 months",
    finding: "The designed Nordic diet increased fruit/vegetable intake and reduced protein, with no detected differences in growth, body composition, energy intake or iron status.",
    limitations: "250 randomised; 206 completed. Does not establish adequacy of an improvised plant-heavy or dairy-free menu or long-term superiority.",
    provenance: "Newly identified within the permitted Nordic family; not confirmed as originally selected.",
  },
  {
    id: "abisFish",
    label: "Swedish ABIS: fish introduction and asthma (Klingberg, 2019)",
    url: "https://link.springer.com/article/10.1007/s00431-018-03312-5",
    family: "Scandinavian / Nordic",
    type: "Observational cohort",
    ageRange: "Infant introduction; asthma follow-up to 15–17 years",
    finding: "Earlier fish introduction was associated with lower subsequent asthma odds in a Swedish cohort of 9,727 children.",
    limitations: "Association is not proof of prevention. Species were not distinguished; no toddler fish dose or frequency was tested.",
    provenance: "Strong match to the original ABIS reference; exact originally selected document remains unconfirmed.",
  },
  {
    id: "swedenEczema",
    label: "Western Sweden: fish introduction and eczema (Alm, 2009)",
    url: "https://pubmed.ncbi.nlm.nih.gov/18818269/",
    family: "Scandinavian / Nordic",
    type: "Observational cohort",
    ageRange: "Fish introduction before 9 months; eczema at 1 year",
    finding: "Earlier fish introduction was associated with lower reported eczema at one year.",
    limitations: "Separate cohort from ABIS. Confounding and reverse causation limit claims; no treatment of existing eczema or toddler frequency rule was tested.",
    provenance: "Likely match to the original eczema reference; exact selected document remains unconfirmed.",
  },
  {
    id: "preventadall",
    label: "Norway/Sweden PreventADALL: early food intervention (2022)",
    url: "https://www.oslo-universitetssykehus.no/48fd25/contentassets/eef1b42a88ae4fbba31d92ff6bf498b6/artikler-pdf/2022-early-food-intervention-and-skin-emollients.pdf",
    family: "Scandinavian / Nordic",
    type: "Randomised trial",
    ageRange: "Introduction from 12–16 weeks; food allergy assessed at 36 months",
    finding: "Early peanut, milk, wheat and egg tastes reduced food allergy at 36 months, mainly peanut allergy.",
    limitations: "Not first introduction at 12–23 months or a three-times-weekly toddler regimen. Fish, sesame and tree nuts were not intervention foods.",
    provenance: "Newly identified within the permitted Nordic family; not confirmed as originally selected.",
  },
];

export function getEvidenceSource(id) {
  return EVIDENCE_SOURCES.find((item) => item.id === id);
}
